project:
  type: website

website:
  favicon: www/logo.png
  title: "Water Action Volunteers"
  back-to-top-navigation: true
  navbar:
    logo: www/header.png
    title: false
    left:
      - page-baseline-monitoring.qmd
      - page-habitat-assessment.qmd
      - page-project-red.qmd
      - page-snapshot-day.qmd

format:
  html:
    theme: cosmo
    css: www/styles.css
    toc: true
    toc-expand: true
    fig-align: center
    fig-height: 5
    fig-width: 8
    code-fold: true

editor: visual

execute:
  freeze: auto
  echo: false
  warning: false

