project:
  type: website

website:
  favicon: www/logo.png
  title: "Water Action Volunteers"
  back-to-top-navigation: true
  navbar:
    logo: www/header.png
    title: false
    left:
      - annual-monitoring-summary.qmd
      - habitat-assessment-summary.qmd
      - project-red-summary.qmd
      - snapshot-day-summary.qmd

format:
  html:
    theme: cosmo
    css: www/styles.css
    toc: true
    toc-expand: true
    fig-align: center
    fig-height: 5
    fig-width: 8
    code-fold: true

editor: visual

execute:
  freeze: auto
  echo: false
  warning: false

