project:
  type: website

website:
  favicon: logo.png
  title: "Water Action Volunteers"
  back-to-top-navigation: true
  navbar:
    logo: header.png
    title: false
    left:
      - annual-monitoring-summary.qmd
      - habitat-assessment-summary.qmd
      - project-red-summary.qmd
      - snapshot-day-summary.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: auto

